version: '3.5'

services:
  backend:
    container_name: backend
    image: backend:2.0.6
    build:
      context: ./
      dockerfile: backend/Dockerfile
    volumes:
      - /home/alejandro_arteaga/EntregaFinal/grpc_example/:/home/src/interface
    command: [python, backend.py]

  ui:
    container_name: interface
    image: interface:2.0.6
    build:
      context: ./
      dockerfile: interface/Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/alejandro_arteaga/EntregaFinal/grpc_example:/home/src/interface
    environment:
      - DISPLAY=host.docker.internal:0.0
    command: [python, interface.py]